[build]
  command = "make build"
  functions = "functions"
  publish = "./"

[build.environment]
GO_VERSION="1.16"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/fitness/:splat"
  status = 200
  force = true
